[project]
name = "electrify-gb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.0",
    "langchain-anthropic>=0.3.22",
]
